version: "3.7"
services:
  node-red:
    restart: always
    container_name: node-red
    image: nrchkb/node-red-homekit
    environment:
      - TZ=Europe/Moscow
    network_mode: host
    volumes:
      - ./data/node-red:/data
  zigbee2mqtt:
    container_name: zigbee2mqtt
    image: koenkk/zigbee2mqtt
    volumes:
      - ./data/zigbee2mqtt:/app/data
    devices:
      - /dev/ttyACM0:/dev/ttyACM0
      - /dev/ttyUSB0:/dev/ttyUSB0
    restart: always
    network_mode: host
    privileged: true
    environment:
      - TZ=Europe/Moscow
  mosquitto:
    container_name: mosquitto
    image: eclipse-mosquitto:1.6.13
    restart: always
    ports:
      - 1883:1883
